CREATE TABLE IF NOT EXISTS notify(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,body TEXT, content DATE,date TEXT, status TEXT);   
CREATE TABLE IF NOT EXISTS setup(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT,value TEXT);     
CREATE TABLE IF NOT EXISTS user(id INTEGER PRIMARY KEY AUTOINCREMENT,dni TEXT, name TEXT, lastname TEXT , email TEXT, estacivi TEXT, gender TEXT, token TEXT, divece TEXT);      
/*INSERT RECORDS*/
INSERT or IGNORE INTO setup(type, value) VALUES ('NOTIFY','1');